#!/bin/bash

# テーマの設定を読み込み
source ${HOME}/.power-level-10k.sh

# Oh My Zshの設定を読み込み
source ${HOME}/.oh-my-zsh.sh

# zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Node.js
## Volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
